### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bw-yuhogg** [pmd/pmd-emacs#3]
Would you be willing to tag a release of this repo? The Homebrew-emacs maintainers are okay with formulae that don't have stable releases, but they would prefer having a stable version.

Thanks!

**Comment by adangel** [comment]
Just done:
https://github.com/pmd/pmd-emacs/releases/tag/0.8
https://github.com/pmd/pmd-emacs/tree/0.8

Let me know, if you need something else :)
